### ISSUE TITLE
Auto-increment counter for tracks

### ISSUE THREAD

**Issue by astrofrog** [astrofrog/robo-ph#17]
Maybe can use last track in public RSS feed

**Comment by astrokatie** [comment]
Eventual plan: get track numbers from number of items currently in RSS feed. Current workaround: have a file with a counter in the repo.

**Comment by astrofrog** [comment]
I've actually gone down a completely different route which should be much more robust - count the number of weekdays since the first podcast. I think this is the best way to go about it and works regardless of whether the RSS feed is accessible, up-to-date, etc.
